#服务名称
spring:
  application:
    name: config-server
  #Git的配置信息
  cloud:
    config:
      server:
        git:
          #配置仓库的位置
          uri: https://github.com/mqs515/config-server
          #配置仓库下的相对搜索位置，可以配置多个
          search-paths: /config-repo
          #访问Git仓库的用户名【可以乱写】
          username: username
          #访问Git仓库的密码【可以乱写】
          password: password
#端口号
server:
  port: 8888

#配置服务注册中心
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:5555/eureka/
