#服务名称
spring:
  application:
    name: config-server
  #Git的配置信息
  cloud:
    config:
      server:
        git:
          #配置仓库的位置
          uri:
          #配置仓库下的相对搜索位置，可以配置多个
          search-paths:
          #访问Git仓库的用户名
          username:
          #访问Git仓库的密码
          password:
#端口号
server:
  port: 8888
